spring.application.name=api_2
spring.datasource.url=jdbc:mysql://localhost:3306/post_criar
spring.datasource.username=root
spring.datasource.password=25092402
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update